#!/bin/bash
######################Archphile Creation Script for Cubox-i############################
clear
red='\e[0;31m'
NC='\e[0m'
# Changing Root password
echo -e "${red}Change the root password...${NC}" 
passwd

# Changing hostname
echo -e "${red}Changing your hostname...${NC}" 
hostnamectl set-hostname archphile

# /etc/motd text
echo -e "${red}Downloading sample /etc/motd file...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/motd-cubox -O /etc/motd
nano /etc/motd

# Changing DNS servers
echo -e "${red}Changing to Google DNS servers...${NC}" 
systemctl disable systemd-resolved
systemctl mask systemd-resolved
rm /etc/resolv.conf
cat > /etc/resolv.conf <<"EOF"
# Google DNS
nameserver 8.8.8.8
nameserver 8.8.4.4
# Opendns
#nameserver 208.67.222.222 
#nameserver 208.67.220.220
EOF
echo -e "${red}Disallowing dhcpcd to change DNS servers...${NC}" 
echo "nohook resolv.conf" >>/etc/dhcpcd.conf

# Disabling various modules
echo -e "${red}Disabling various modules...${NC}" 
cat > /etc/modprobe.d/blacklist.conf <<"EOF"
blacklist gpio_ir_recv
blacklist ir_sony_decoder
blacklist ir_rc6_decoder
blacklist ir_rc5_sz_decoder
blacklist ir_rc5_decoder
blacklist ir_nec_decoder
blacklist ir_jvc_decoder
blacklist ir_lirc_codec
blacklist lirc_dev
blacklist ir_lirc_codec
blacklist rpcsec_gss_krb5
EOF

# Network Configuration
echo -e "${red}Changing netctl network configuration...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/archphile-network -O /etc/netctl/archphile-network
systemctl disable systemd-networkd
systemctl mask systemd-networkd
netctl enable archphile-network

# Disabling ipv6
# "net.ipv6.conf.all.disable_ipv6=1" added throught archphile-optimize package 
sed -e '/::1/ s/^#*/#/' -i /etc/hosts
echo >>/etc/dhcpcd.conf
echo "#Disable ipv6 connectivity" >>/etc/dhcpcd.conf
echo "noipv6rs" >>/etc/dhcpcd.conf
echo "noipv6" >>/etc/dhcpcd.conf

# Locale and timezone configuration
systemctl disable systemd-timesyncd
systemctl mask systemd-timesyncd
pacman -Sy ntp --noconfirm
echo -e "${red}Changing locale, timezone and ntp configuration...${NC}" 
sed -i 's/^#en_US.UTF-8 UTF-8.*/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG="en_US.UTF-8"" > /etc/locale.conf
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Athens /etc/localtime
wget https://raw.githubusercontent.com/archphile/recipe/master/files/ntp.conf -O /etc/ntp.conf

# /etc/fstab tweaking and linking .bash_history to /dev/null
echo -e "${red}Changing fstab entries...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/fstab-cubox -O /etc/fstab

echo -e "${red}Linking .bash_history to /dev/null...${NC}" 
rm /root/.bash_history
ln -sf /dev/null ~/.bash_history

# Adding Archphile repository and installing needed packages
echo -e "${red}Adding Archphile Repository...${NC}" 
cat >> /etc/pacman.conf <<"EOF"
#[arm7-testing]
#SigLevel = Never
#Server = http://archphile.org/repo/arm7-testing

[archphile]
SigLevel = Never
Server = http://archphile.org/repo/arm7
EOF

echo -e "${red}Updating system and installing needed packages...${NC}" 
pacman -Syu --noconfirm
pacman -S mpd-archphile mpc ympd-archphile archphile-optimize upmpdcli-archphile shairport-archphile alsa-utils cifs-utils nfs-utils udevil ntfs-3g htop avahi wpa_supplicant wireless_tools iw dhcpcd firmware-brcm43xx mongoose hd-idle --noconfirm

# alternative method for wifi drivers installation
#echo -e "${red}Installing wifi drivers...${NC}" 
#pacman -Rcsn firmware-brcm43xx --noconfirm
#wget https://raw.githubusercontent.com/archphile/recipe/master/files/cubox_wireless_firmware/brcmfmac4329-sdio.txt
#wget https://raw.githubusercontent.com/archphile/recipe/master/files/cubox_wireless_firmware/brcmfmac4330-sdio.txt
#mv brcmfmac4329-sdio.txt /usr/lib/firmware/brcm/
#mv brcmfmac4330-sdio.txt /usr/lib/firmware/brcm/

# Temporary telnet installation and configuration until ssh over wifi is fixed:
#echo -e "${red}Installing and configuring telnet - You will have to manually enable the service...${NC}"
#pacman -S xinetd
#sed -i 's/^	disable			= yes*/	disable			= no/' /etc/xinetd.d/telnet

# Removing unneeded packages and cleaning pacman cache
echo -e "${red}Removing unneeded packages and cleaning pacman cache...${NC}" 
pacman -Rcsn lvm2 mdadm reiserfsprogs xfsprogs man-db which s-nail licenses jfsutils gettext logrotate --noconfirm
systemctl disable cronie
systemctl mask cronie
pacman -Scc

# Fetching mpd.conf for cubox-i
echo -e "${red}Fetching mpd.conf for cubox-i...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/mpd.conf-cubox -O /etc/mpd.conf

# Bypassing new User=mpd systemd configuration 
echo -e "${red}Fetching user.conf in order to bypass User=mpd...${NC}" 
mkdir /etc/systemd/system/mpd.service.d
wget https://raw.githubusercontent.com/archphile/recipe/master/files/user.conf -O /etc/systemd/system/mpd.service.d/user.conf

# Setting multi-user.target as the new default target
echo -e "${red}Setting default systemd target...${NC}" 
systemctl set-default -f multi-user.target

# Enabling systemd services
echo -e "${red}Enabling needed Systemd services...${NC}" 
systemctl enable mpd
systemctl enable ympd
systemctl enable archphile
systemctl enable avahi-daemon

# Creating stuff for MPD
echo -e "${red}Creating directories needed by MPD and downloading webradios...${NC}" 
mkdir /mnt/nas-nfs
mkdir /mnt/nas-samba
wget https://github.com/archphile/recipe/raw/master/files/webradio.tar.gz
tar xvfz webradio.tar.gz
mv webradio /mnt/
chown -R root:root /mnt/webradio
rm webradio.tar.gz
mkdir /mnt/usb-disk
mkdir /var/lib/mpd/music
chown -R mpd /var/lib/mpd
cd /var/lib/mpd/music
ln -s /mnt/nas-nfs
ln -s /mnt/nas-samba
ln -s /mnt/webradio
ln -s /mnt/usb-disk
gpasswd -a mpd audio

# setting the USB Dac as default sound card
echo -e "${red}Setting the USB DAC as the default sound card...${NC}" 
cat > /etc/asound.conf <<"EOF"
pcm.!default {
        type hw
        card 2
}

ctl.!default {
        type hw
        card 2
}
EOF

# udevil configuration
echo -e "${red}Creating udevil configuration and enabling devmon service...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/udevil.conf -O /etc/udevil/udevil.conf
systemctl enable devmon@root

## limits.conf configuration
#echo -e "${red}Changing /etc/security/limits.conf configuration...${NC}" 
#https://raw.githubusercontent.com/archphile/recipe/master/files/limits.conf
#mv limits.conf /etc/security/limits.conf

# journald.conf configuration and /var/log deletion
echo -e "${red}Changing journald.conf configuration and deleting /var/log...${NC}" 
sed -i 's/^#Storage=auto.*/Storage=none/' /etc/systemd/journald.conf
#systemctl disable systemd-journald
#systemctl mask systemd-journald
#systemctl mask systemd-journal-flush.service
rm -R /var/log

# disabling systemd-logind
#echo -e "${red}Disabling systemd-logind...${NC}"
#systemctl disable systemd-logind
#systemctl mask systemd-logind

# turning off wifi power management
echo -e "${red}Turning off wifi power management...${NC}" 
sed -i 's/^#iwconfig wlan0 power off.*/iwconfig wlan0 power off/' /usr/bin/archphile-optimize

# temporary fix for ControlGroup and ControlGroupAttribute mpd.service options
echo -e "${red}Applying temporart fix for mpd.service ...${NC}" 
sed -e '/ControlGroup/ s/^#*/#/' -i  /usr/lib/systemd/system/mpd.service
sed -e '/ControlGroupAttribute/ s/^#*/#/' -i  /usr/lib/systemd/system/mpd.service
systemctl reenable mpd

# Applying various tweaks/mods
echo -e "${red}Applying various tweaks/mods ...${NC}" 
echo "Archphile \r (\l)" > /etc/issue
sed -i 's/#Color/Color/' /etc/pacman.conf

# settings for fetching local cover art using Mpdroid and Mpod
echo -e "${red}Making symlinks for fetching local cover art${NC}" 
mkdir -p /var/www/covers
mkdir -p /var/www/Music
ln -s /var/lib/mpd/music /var/www/covers
ln -s /var/lib/mpd/music /var/www/Music

# disks spin-down configuration
echo -e "${red}Fetching udev rules for hdparm...${NC}" 
mkdir /opt/archphile
wget https://raw.githubusercontent.com/archphile/recipe/master/files/50-hdparm.rules-onedisk -O /opt/archphile/50-hdparm.rules-onedisk
wget https://raw.githubusercontent.com/archphile/recipe/master/files/50-hdparm.rules-manydisks -O /opt/archphile/50-hdparm.rules-manydisks
wget https://raw.githubusercontent.com/archphile/recipe/master/files/hd-idle -O /etc/conf.d/hd-idle

# system cleanup
echo -e "${red}Cleaning up system...${NC}" 
rm /etc/ssh/ssh_host_*
rm /root/archphile-create-script*

echo -e "${red}PLEASE REBOOT YOUR SYSTEM IMMEDIATELY!!!!!!${NC}" 








