#!/bin/bash
######################Archphile Creation Script for Udoo V3.2############################
clear
red='\e[0;31m'
NC='\e[0m'
# Changing Root password
echo -e "${red}Change the root password...${NC}" 
passwd

# Changing hostname
echo -e "${red}Changing your hostname...${NC}" 
hostnamectl set-hostname archphile

# /etc/motd text
echo -e "${red}Downloading sample /etc/motd file...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/motd-udoo
mv motd-udoo /etc/motd
nano /etc/motd

# Changing DNS servers
echo -e "${red}Changing to Google DNS servers...${NC}" 
systemctl disable systemd-resolved
systemctl mask systemd-resolved
rm /etc/resolv.conf
cat > /etc/resolv.conf <<"EOF"
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF

echo -e "${red}Disallowing dhcpcd to change DNS servers...${NC}" 
echo "nohook resolv.conf" >>/etc/dhcpcd.conf

# Disabling various modules
echo -e "${red}Disabling various modules...${NC}" 
cat > /etc/modprobe.d/blacklist.conf <<"EOF"
blacklist rpcsec_gss_krb5
blacklist imxdrm
blacklist imx-hdmi
blacklist imx_ipuv3_crtc
blacklist imx_ipu_v3
EOF

# Network Configuration
echo -e "${red}Changing netctl network configuration...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/archphile-network
mv archphile-network /etc/netctl/archphile-network
systemctl disable systemd-networkd
systemctl mask systemd-networkd
netctl enable archphile-network

# Disabling ipv6
echo "net.ipv6.conf.all.disable_ipv6=1" > /etc/sysctl.d/disableipv6.conf
echo 'blacklist ipv6' >> /etc/modprobe.d/blacklist.conf
sed -i '/::/s%^%#%g' /etc/hosts

# Locale and timezone configuration
systemctl disable systemd-timesyncd
systemctl mask systemd-timesyncd
pacman -Sy ntp --noconfirm
echo -e "${red}Changing locale, timezone and ntp configuration...${NC}" 
sed -i 's/^#en_US.UTF-8 UTF-8.*/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG="en_US.UTF-8"" > /etc/locale.conf
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Athens /etc/localtime
wget https://raw.githubusercontent.com/archphile/recipe/master/files/ntp.conf
mv ntp.conf /etc/ntp.conf

# /etc/fstab tweaking and linking .bash_history to /dev/null
echo -e "${red}Changing fstab entries...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/fstab-udoo
mv fstab-udoo /etc/fstab 
echo -e "${red}Linking .bash_history to /dev/null...${NC}" 
rm /root/.bash_history
ln -sf /dev/null ~/.bash_history

# Adding Archphile repository and installing needed packages
echo -e "${red}Adding Archphile Repository...${NC}" 
cat >> /etc/pacman.conf <<"EOF"
[archphile]
SigLevel = Never
Server = http://archphile.org/repo/arm7
EOF

echo -e "${red}Updating system and installing needed packages...${NC}" 
pacman -Syu --noconfirm
pacman -S mpd-archphile mpc ympd-archphile archphile-optimize upmpdcli-archphile shairport-archphile alsa-utils cifs-utils nfs-utils udevil ntfs-3g htop avahi wpa_supplicant wireless_tools iw dhcpcd --noconfirm

# Removing unneeded packages and cleaning pacman cache
echo -e "${red}Removing unneeded packages and cleaning pacman cache...${NC}" 
pacman -Rcsn lvm2 mdadm reiserfsprogs xfsprogs man-db --noconfirm
systemctl disable cronie
systemctl mask cronie
pacman -Scc

# Bypassing new User=mpd systemd configuration 
echo -e "${red}Fetching user.conf in order to bypass User=mpd...${NC}" 
mkdir /etc/systemd/system/mpd.service.d
wget https://raw.githubusercontent.com/archphile/recipe/master/files/user.conf
mv user.conf /etc/systemd/system/mpd.service.d/

# Setting multi-user.target as the new default target
echo -e "${red}Setting default systemd target...${NC}" 
systemctl set-default -f multi-user.target

# Enabling systemd services
echo -e "${red}Enabling needed Systemd services...${NC}" 
systemctl enable mpd
systemctl enable ympd
systemctl enable archphile
systemctl enable avahi-daemon

# Creating stuff for MPD
echo -e "${red}Creating directories needed by MPD and downloading webradios...${NC}" 
mkdir /mnt/nas-nfs
mkdir /mnt/nas-samba
wget https://github.com/archphile/recipe/raw/master/files/webradio.tar.gz
tar xvfz webradio.tar.gz
mv webradio /mnt/
chown -R root:root /mnt/webradio
rm webradio.tar.gz
mkdir /mnt/usb-disk
mkdir /var/lib/mpd/music
chown -R mpd /var/lib/mpd
cd /var/lib/mpd/music
ln -s /mnt/nas-nfs
ln -s /mnt/nas-samba
ln -s /mnt/webradio
ln -s /mnt/usb-disk
gpasswd -a mpd audio

# udevil configuration
echo -e "${red}Creating udevil configuration and enabling devmon service...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/udevil.conf
mv udevil.conf /etc/udevil/udevil.conf
systemctl enable devmon@root

## limits.conf configuration
#echo -e "${red}Changing /etc/security/limits.conf configuration...${NC}" 
#wget http://archphile.org/lab/files/limits.conf
#mv limits.conf /etc/security/limits.conf

# journald.conf configuration and /var/log deletion
echo -e "${red}Changing journald.conf configuration and deleting /var/log...${NC}" 
sed -i 's/^#Storage=auto.*/Storage=none/' /etc/systemd/journald.conf
#systemctl disable systemd-journald
#systemctl mask systemd-journald
#systemctl mask systemd-journal-flush.service
rm -R /var/log

# disabling systemd-logind
#echo -e "${red}Disabling systemd-logind...${NC}"
#systemctl disable systemd-logind
#systemctl mask systemd-logind

# updating to latest ralink wireless firmware
echo -e "${red}Updating wireless firmware rt2870usb to version 0.33...${NC}" 
wget https://github.com/archphile/recipe/raw/master/files/udoo_wireless_firmware/rt2870.bin
mv rt2870.bin /lib/firmware/rt2870.bin

# turning off wifi power management
echo -e "${red}Turning off wifi power management...${NC}" 
sed -i 's/^#iwconfig wlan0 power off.*/iwconfig wlan0 power off/' /usr/bin/archphile-optimize

# fix for rt2800usb wireless driver
echo -e "${red}Applying extra options for rt2800usb module...${NC}" 
cat >> /etc/modprobe.d/rt2800usb.conf <<"EOF"
options rt2800usb nohwcrypt=1
EOF

# temporary fix for ControlGroup and ControlGroupAttribute mpd.service options
echo -e "${red}Applying temporart fix for mpd.service ...${NC}" 
sed -e '/ControlGroup/ s/^#*/#/' -i  /usr/lib/systemd/system/mpd.service
sed -e '/ControlGroupAttribute/ s/^#*/#/' -i  /usr/lib/systemd/system/mpd.service
systemctl reenable mpd

# changing /etc/issue message
echo -e "${red}Changing /etc/issue message ...${NC}" 
echo "Archphile \r (\l)" > /etc/issue

echo -e "${red}PLEASE REBOOT YOUR SYSTEM IMMEDIATELY!!!!!!${NC}" 

# Script deletion
rm /root/archphile-create-script*







