#!/bin/bash
######################Archphile Creation Script for Raspberry Pi 2############################
clear
red='\e[0;31m'
NC='\e[0m'

#login as root, delete alarm user and modify ssh to accept root login
echo -e "${red}Give default root password...${NC}" 
su root
echo -e "${red}Deleting alarm user...${NC}" 
userdel -r alarm
echo -e "${red}Setting PermitRootLogin to yes...${NC}" 
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

# Changing Root password
echo -e "${red}Change the root password...${NC}" 
passwd

# Changing hostname
echo -e "${red}Changing your hostname...${NC}" 
hostnamectl set-hostname archphile

# /etc/motd text
echo -e "${red}Downloading sample /etc/motd file...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/motd-rpi -O /etc/motd
nano /etc/motd

# Changing DNS servers
echo -e "${red}Changing to Google DNS servers...${NC}" 
systemctl disable systemd-resolved
systemctl mask systemd-resolved
rm /etc/resolv.conf
cat > /etc/resolv.conf <<"EOF"
# Google DNS
nameserver 8.8.8.8
nameserver 8.8.4.4
# Opendns
#nameserver 208.67.222.222 
#nameserver 208.67.220.220
EOF
echo -e "${red}Disallowing dhcpcd to change DNS servers...${NC}" 
echo "nohook resolv.conf" >>/etc/dhcpcd.conf

# Disabling various modules
echo -e "${red}Disabling various modules...${NC}" 
cat > /etc/modprobe.d/blacklist.conf <<"EOF"
blacklist snd_bcm2835
blacklist rpcsec_gss_krb5
EOF

# Network Configuration
echo -e "${red}Changing netctl network configuration...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/archphile-network -O /etc/netctl/archphile-network
systemctl disable systemd-networkd
systemctl mask systemd-networkd
netctl enable archphile-network

# Disabling ipv6
# "net.ipv6.conf.all.disable_ipv6=1" added throught archphile-optimize package 
sed -e '/::1/ s/^#*/#/' -i /etc/hosts
echo >>/etc/dhcpcd.conf
echo "#Disable ipv6 connectivity" >>/etc/dhcpcd.conf
echo "noipv6rs" >>/etc/dhcpcd.conf
echo "noipv6" >>/etc/dhcpcd.conf

# Locale and timezone configuration
systemctl disable systemd-timesyncd
systemctl mask systemd-timesyncd
pacman -Sy ntp --noconfirm
echo -e "${red}Changing locale, timezone and ntp configuration...${NC}" 
sed -i 's/^#en_US.UTF-8 UTF-8.*/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG="en_US.UTF-8"" > /etc/locale.conf
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Athens /etc/localtime
wget https://raw.githubusercontent.com/archphile/recipe/master/files/ntp.conf -O /etc/ntp.conf

# /etc/fstab tweaking and linking .bash_history to /dev/null
echo -e "${red}Changing fstab entries...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/fstab-rpi -O /etc/fstab
echo -e "${red}Linking .bash_history to /dev/null...${NC}" 
rm /root/.bash_history
ln -sf /dev/null ~/.bash_history

# Adding Archphile repository and installing needed packages
echo -e "${red}Adding Archphile Repository...${NC}" 
cat >> /etc/pacman.conf <<"EOF"
[archphile]
SigLevel = Never
Server = http://archphile.org/repo/arm7
EOF
echo -e "${red}Updating system and installing needed packages...${NC}" 
pacman -Syu --noconfirm
pacman -S mpd-archphile mpc ympd-archphile archphile-optimize i2select upmpdcli-archphile shairport-sync-archphile alsa-utils cifs-utils nfs-utils udevil ntfs-3g htop avahi wpa_supplicant wireless_tools iw dhcpcd mongoose hd-idle tcp_wrappers --noconfirm

# Removing unneeded packages and cleaning pacman cache
echo -e "${red}Removing unneeded packages and cleaning pacman cache...${NC}" 
pacman -Rcsn lvm2 mdadm reiserfsprogs xfsprogs man-db which s-nail licenses jfsutils gettext logrotate --noconfirm
#systemctl disable cronie
#systemctl mask cronie
pacman -Scc

# Bypassing new User=mpd systemd configuration 
#echo -e "${red}Fetching user.conf in order to bypass User=mpd...${NC}" 
#mkdir /etc/systemd/system/mpd.service.d
#wget https://raw.githubusercontent.com/archphile/recipe/master/files/user.conf -O /etc/systemd/system/mpd.service.d/user.conf

# Setting multi-user.target as the new default target
echo -e "${red}Setting default systemd target...${NC}" 
systemctl set-default -f multi-user.target

# Enabling systemd services
echo -e "${red}Enabling needed Systemd services...${NC}" 
systemctl enable mpd
systemctl enable ympd
systemctl enable archphile
systemctl enable avahi-daemon

# Creating stuff for MPD
echo -e "${red}Creating directories needed by MPD and downloading webradios...${NC}" 
mkdir /mnt/nas-nfs
mkdir /mnt/nas-samba
wget https://github.com/archphile/recipe/raw/master/files/webradio.tar.gz
tar xvfz webradio.tar.gz
mv webradio /mnt/
chown -R root:root /mnt/webradio
rm webradio.tar.gz
mkdir /mnt/usb-disk
mkdir /var/lib/mpd/music 
chown -R mpd /var/lib/mpd
cd /var/lib/mpd/music
ln -s /mnt/nas-nfs
ln -s /mnt/nas-samba
ln -s /mnt/webradio
ln -s /mnt/usb-disk
gpasswd -a mpd audio

# Alsa configuration
#echo -e "${red}Creating Alsa configuration...${NC}" 
#cat > /etc/modprobe.d/alsa-base.conf <<"EOF"
##options snd slots=snd_usb_audio,snd_bcm2835
#options snd_usb_audio index=0 nrpacks=8
#EOF

# udevil configuration
echo -e "${red}Creating udevil configuration and enabling devmon service...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/udevil.conf -O /etc/udevil/udevil.conf
systemctl enable devmon@root

## limits.conf configuration
#echo -e "${red}Changing /etc/security/limits.conf configuration...${NC}" 
#wget http://archphile.org/lab/files/limits.conf
#mv limits.conf /etc/security/limits.conf

# journald.conf configuration and /var/log deletion
echo -e "${red}Changing journald.conf configuration and deleting /var/log...${NC}" 
sed -i 's/^#Storage=auto.*/Storage=none/' /etc/systemd/journald.conf
#systemctl disable systemd-journald
#systemctl mask systemd-journald
#systemctl mask systemd-journal-flush.service
rm -R /var/log

# disabling systemd-logind
#echo -e "${red}Disabling systemd-logind...${NC}"
#systemctl disable systemd-logind
#systemctl mask systemd-logind

# disabling power management for edimax wifi dongles
#echo -e "${red}Disabling power management for Edimax wifi dongles...${NC}"
#cat > /etc/modprobe.d/8192cu.conf <<"EOF"
##options 8192cu rtw_power_mgnt=0 rtw_enusbss=0
#EOF

# turning off wifi power management
#echo -e "${red}Turning off wifi power management...${NC}" 
#sed -i 's/^#iwconfig wlan0 power off.*/iwconfig wlan0 power off/' /usr/bin/archphile-optimize

# temporary fix for ControlGroup and ControlGroupAttribute mpd.service options
echo -e "${red}Applying temporart fix for mpd.service ...${NC}" 
sed -e '/ControlGroup/ s/^#*/#/' -i  /usr/lib/systemd/system/mpd.service
sed -e '/ControlGroupAttribute/ s/^#*/#/' -i  /usr/lib/systemd/system/mpd.service
systemctl reenable mpd

# Applying various tweaks/mods
echo -e "${red}Applying various tweaks/mods ...${NC}" 
echo "Archphile \r (\l)" > /etc/issue
sed -i 's/#Color/Color/' /etc/pacman.conf

# settings for fetching local cover art using Mpdroid and Mpod
echo -e "${red}Making symlinks for fetching local cover art${NC}" 
mkdir -p /var/www/covers
mkdir -p /var/www/Music
ln -s /var/lib/mpd/music /var/www/covers
ln -s /var/lib/mpd/music /var/www/Music

# disks spin-down configuration
echo -e "${red}Fetching udev rules for hdparm...${NC}" 
mkdir /opt/archphile
wget https://raw.githubusercontent.com/archphile/recipe/master/files/50-hdparm.rules-onedisk -O /opt/archphile/50-hdparm.rules-onedisk
wget https://raw.githubusercontent.com/archphile/recipe/master/files/50-hdparm.rules-manydisks -O /opt/archphile/50-hdparm.rules-manydisks
wget https://raw.githubusercontent.com/archphile/recipe/master/files/hd-idle -O /etc/conf.d/hd-idle

# Allowing MPD in hosts.allow (tcp_wrappers)
echo -e "${red}Putting MPD in hosts.allow...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/hosts.allow -O /etc/hosts.allow

# change the password in first login
echo -e "${red}Setting a password change for next login...${NC}" 
chage -d 0 root

# system cleanup
echo -e "${red}Cleaning up system...${NC}" 
rm /etc/ssh/ssh_host_*
rm /root/archphile-create-script*

echo -e "${red}PLEASE REBOOT YOUR SYSTEM IMMEDIATELY!!!!!!${NC}" 




