#!/bin/bash
######################Archphile Creation Script for Odroid C1+############################
clear
red='\e[0;31m'
NC='\e[0m'

# Deleting alarm user and changing Root password
echo -e "${red}Deleting alarm user...${NC}" 
su
cd /root
userdel -r alarm
echo -e "${red}Change the root password...${NC}" 
passwd

# Changing hostname
echo -e "${red}Changing your hostname...${NC}" 
hostnamectl set-hostname archphile

# /etc/motd text
echo -e "${red}Downloading sample /etc/motd file...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/motd-odroidc1 -O /etc/motd
nano /etc/motd

# Changing DNS servers
echo -e "${red}Changing to Google DNS servers...${NC}" 
systemctl disable systemd-resolved
systemctl mask systemd-resolved
rm /etc/resolv.conf
cat > /etc/resolv.conf <<"EOF"
# Google DNS
nameserver 8.8.8.8
nameserver 8.8.4.4
# Opendns
#nameserver 208.67.222.222 
#nameserver 208.67.220.220
EOF
echo -e "${red}Disallowing dhcpcd to change DNS servers...${NC}" 
echo "nohook resolv.conf" >>/etc/dhcpcd.conf

# Disabling various modules
echo -e "${red}Disabling various modules...${NC}" 
cat > /etc/modprobe.d/blacklist.conf <<"EOF"

EOF

# Network Configuration
echo -e "${red}Changing netctl network configuration...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/archphile-network -O /etc/netctl/archphile-network
systemctl disable systemd-networkd
systemctl mask systemd-networkd
netctl enable archphile-network

# Disabling ipv6
# "net.ipv6.conf.all.disable_ipv6=1" added throught archphile-optimize package 
sed -e '/::1/ s/^#*/#/' -i /etc/hosts
echo >>/etc/dhcpcd.conf
echo "#Disable ipv6 connectivity" >>/etc/dhcpcd.conf
echo "noipv6rs" >>/etc/dhcpcd.conf
echo "noipv6" >>/etc/dhcpcd.conf

# Locale and timezone configuration
systemctl disable systemd-timesyncd
systemctl mask systemd-timesyncd
pacman -Sy ntp --noconfirm
echo -e "${red}Changing locale, timezone and ntp configuration...${NC}" 
sed -i 's/^#en_US.UTF-8 UTF-8.*/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG="en_US.UTF-8"" > /etc/locale.conf
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Athens /etc/localtime
wget https://raw.githubusercontent.com/archphile/recipe/master/files/ntp.conf -O /etc/ntp.conf

# /etc/fstab tweaking and linking .bash_history to /dev/null
echo -e "${red}Changing fstab entries...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/fstab-odroidc1 -O /etc/fstab
echo -e "${red}Linking .bash_history to /dev/null...${NC}" 
rm /root/.bash_history
ln -sf /dev/null ~/.bash_history

# Adding Archphile repository and installing needed packages
echo -e "${red}Adding Archphile Repository...${NC}" 
cat >> /etc/pacman.conf <<"EOF"
[archphile]
SigLevel = Never
Server = http://archphile.org/repo/arm7

[playground]
SigLevel = Never
Server = http://archphile.org/repo/playground/playground-arm7
EOF

echo -e "${red}Updating system and installing needed packages...${NC}" 
pacman -Syu --noconfirm
pacman -S mpd-archphile mpc ympd-archphile archphile-optimize upmpdcli-archphile shairport-sync alsa-utils cifs-utils nfs-utils udevil ntfs-3g htop avahi wpa_supplicant wireless_tools iw dhcpcd mongoose hd-idle alsacap samba --noconfirm

# Removing unneeded packages and cleaning pacman cache
echo -e "${red}Removing unneeded packages and cleaning pacman cache...${NC}" 
pacman -Rcsn lvm2 mdadm reiserfsprogs xfsprogs man-db which s-nail licenses jfsutils gettext logrotate --noconfirm
#systemctl disable cronie
#systemctl mask cronie
pacman -Scc

# Bypassing new User=mpd systemd configuration 
echo -e "${red}Fetching user.conf in order to bypass User=mpd...${NC}" 
mkdir /etc/systemd/system/mpd.service.d
wget https://raw.githubusercontent.com/archphile/recipe/master/files/user.conf -O /etc/systemd/system/mpd.service.d/user.conf

# Setting multi-user.target as the new default target
echo -e "${red}Setting default systemd target...${NC}" 
systemctl set-default -f multi-user.target

# Enabling systemd services
echo -e "${red}Enabling needed Systemd services...${NC}" 
systemctl enable mpd
systemctl enable ympd
systemctl enable archphile
systemctl enable avahi-daemon

# Creating stuff for MPD
echo -e "${red}Creating directories needed by MPD and downloading webradios...${NC}" 
mkdir /mnt/nas-nfs
mkdir /mnt/nas-samba
wget https://github.com/archphile/recipe/raw/master/files/webradio.tar.gz
tar xvfz webradio.tar.gz
mv webradio /mnt/
chown -R root:root /mnt/webradio
rm webradio.tar.gz
mkdir /mnt/usb-disk
mkdir /var/lib/mpd/music
chown -R mpd /var/lib/mpd
cd /var/lib/mpd/music
ln -s /mnt/nas-nfs
ln -s /mnt/nas-samba
ln -s /mnt/webradio
ln -s /mnt/usb-disk
gpasswd -a mpd audio

# setting the USB Dac as default sound card
echo -e "${red}Setting the USB DAC as the default sound card...${NC}" 
cat > /etc/asound.conf <<"EOF"
pcm.!default {
        type hw
        card 1
}

ctl.!default {
        type hw
        card 1
}
EOF

# udevil configuration
echo -e "${red}Creating udevil configuration and enabling devmon service...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/udevil.conf -O /etc/udevil/udevil.conf
systemctl enable devmon@root

## limits.conf configuration
#echo -e "${red}Changing /etc/security/limits.conf configuration...${NC}" 
#wget http://archphile.org/lab/files/limits.conf
#mv limits.conf /etc/security/limits.conf

# journald.conf configuration and /var/log deletion
echo -e "${red}Changing journald.conf configuration and deleting /var/log...${NC}" 
sed -i 's/^#Storage=auto.*/Storage=none/' /etc/systemd/journald.conf
#systemctl disable systemd-journald
#systemctl mask systemd-journald
#systemctl mask systemd-journal-flush.service
rm -R /var/log

# disabling systemd-logind
#echo -e "${red}Disabling systemd-logind...${NC}"
#systemctl disable systemd-logind
#systemctl mask systemd-logind

# turning off wifi power management
#echo -e "${red}Turning off wifi power management...${NC}" 
#sed -i 's/^#iwconfig wlan0 power off.*/iwconfig wlan0 power off/' /usr/bin/archphile-optimize

# temporary fix for ControlGroup and ControlGroupAttribute mpd.service options
#echo -e "${red}Applying temporart fix for mpd.service ...${NC}" 
#sed -e '/ControlGroup/ s/^#*/#/' -i  /usr/lib/systemd/system/mpd.service
#sed -e '/ControlGroupAttribute/ s/^#*/#/' -i  /usr/lib/systemd/system/mpd.service
#systemctl reenable mpd

# Applying various tweaks/mods
echo -e "${red}Applying various tweaks/mods ...${NC}" 
echo "Archphile \r (\l)" > /etc/issue
sed -i 's/#Color/Color/' /etc/pacman.conf

# settings for fetching local cover art using Mpdroid and Mpod
echo -e "${red}Making symlinks for fetching local cover art${NC}" 
mkdir -p /var/www/covers
mkdir -p /var/www/Music
ln -s /var/lib/mpd/music /var/www/covers
ln -s /var/lib/mpd/music /var/www/Music

# disks spin-down configuration
echo -e "${red}Fetching udev rules for hdparm...${NC}" 
mkdir /opt/archphile
wget https://raw.githubusercontent.com/archphile/recipe/master/files/50-hdparm.rules-onedisk -O /opt/archphile/50-hdparm.rules-onedisk
wget https://raw.githubusercontent.com/archphile/recipe/master/files/50-hdparm.rules-manydisks -O /opt/archphile/50-hdparm.rules-manydisks
wget https://raw.githubusercontent.com/archphile/recipe/master/files/hd-idle -O /etc/conf.d/hd-idle

# sharing usb disks with samba configuration
echo -e "${red}Fetching samba configuration for sharing usb disks...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/smb.conf -O /etc/samba/smb.conf
echo -e "${red}In order to share your usb disk please enable and start smbd and nmbd service...${NC}"

# Setting configuration for shairport-sync
echo -e "${red}Setting shairport-sync configuration..${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/shairport-sync.conf -O /etc/shairport-sync.conf

# change the password in first login
#echo -e "${red}Setting a password change for next login...${NC}" 
#change -d 0 root

#fixing root permissions for sshd
echo -e "${red}Setting PermitRootLogin to yes...${NC}" 
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

# IRQ affinity options
echo -e "${red}Adding optional IRQ affinity options...${NC}" 
wget https://raw.githubusercontent.com/archphile/recipe/master/files/irq-archphile-odroid -O /usr/bin/irq-archphile
chmod +x /usr/bin/irq-archphile

# kernel downgrade to solve USB issues
echo -e "${red}Downgrading kernel to 3.10.80-14...${NC}" 
wget http://archphile.org/lab/odroid/linux-odroid-c1-3.10.80-14-armv7h.pkg.tar.xz
pacman -U http://archphile.org/lab/odroid/linux-odroid-c1-3.10.80-14-armv7h.pkg.tar.xz --no-confirm
rm linux-odroid-c1-3.10.80-14-armv7h.pkg.tar.xz
pacman -Scc

# set USB DAC as default MPD soundcard
sed -i 's/^device          "hw:0,0".*/device          "hw:1,0"/' /etc/mpd.conf

# Disable hearbeat led on Odroid C1+
#sed -i 's/^#echo default-on.*/echo default-on > /sys/class/leds/blue\:heartbeat/trigger/' /usr/bin/archphile-optimize

# system cleanup
echo -e "${red}Cleaning up system...${NC}" 
rm /etc/ssh/ssh_host_*
rm /root/archphile-create-script*

echo -e "${red}PLEASE REBOOT YOUR SYSTEM IMMEDIATELY!!!!!!${NC}" 
