#!/bin/bash

# This script helps you choose and configure your desired i2s dac or revert to usb dac configuration which 
# is the default in Archphile.

clear
red='\e[0;31m'
NC='\e[0m'
echo -e "${red}I2s DAC CONFIGURATION TOOL${NC}"
echo -e "${red}---------------------------${NC}"
echo -e " "
PS3='Please select the i2s dac you want to configure: '
options=("Hifiberry" "Hifiberry Plus" "Hifiberry Digi" "Iqaudio" "Iqaudio Plus" "Mamboberry" "Usb Dac Configuration (Default)" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Hifiberry")
            cp /boot/config.txt.orig /boot/config.txt
            sed -i '0,/#device_tree_overlay=hifiberry-dac/s//device_tree_overlay=hifiberry-dac/' /boot/config.txt
            echo -e "${red}Please reboot immediately using 'systemctl reboot' command...${NC}"  
            exit
           ;;
        "Hifiberry Plus")
            cp /boot/config.txt.orig /boot/config.txt
            sed -i '0,/#device_tree_overlay=hifiberry-dacplus/s//device_tree_overlay=hifiberry-dacplus/' /boot/config.txt
            echo -e "${red}Please reboot immediately using 'systemctl reboot' command...${NC}"    
            exit
            ;;
        "Hifiberry Digi")
            cp /boot/config.txt.orig /boot/config.txt
            sed -i '0,/#device_tree_overlay=hifiberry-digi/s//device_tree_overlay=hifiberry-digi/' /boot/config.txt
            echo -e "${red}Please reboot immediately using 'systemctl reboot' command...${NC}"    
	    exit
	    ;;
	    "Iqaudio")
            cp /boot/config.txt.orig /boot/config.txt
            sed -i '0,/#device_tree_overlay=iqaudio-dac/s//device_tree_overlay=iqaudio-dac/' /boot/config.txt
            echo -e "${red}Please reboot immediately using 'systemctl reboot' command...${NC}"    
	    exit
	    ;;
	    "Iqaudio Plus")
	    cp /boot/config.txt.orig /boot/config.txt
            sed -i '0,/#device_tree_overlay=iqaudio-dacplus/s//device_tree_overlay=iqaudio-dacplus/' /boot/config.txt
            echo -e "${red}Please reboot immediately using 'systemctl reboot' command...${NC}"   
            exit
            ;;
	    "Mamboberry")
	    cp /boot/config.txt.orig /boot/config.txt
            sed -i '0,/#device_tree_overlay=hifiberry-dac/s//device_tree_overlay=hifiberry-dac/' /boot/config.txt
            echo -e "${red}Please reboot immediately using 'systemctl reboot' command...${NC}" 
            exit
            ;;
	    "Usb Dac Configuration (Default)")
	    cp /boot/config.txt.orig /boot/config.txt
	    echo -e "${red}Please reboot immediately using 'systemctl reboot' command...${NC}" 
            exit
	    ;;
        "Quit")
           break
            ;;
        *) echo Invalid option - Please choose 1-8;;
    esac
done




